const $ = (id) => document.getElementById(id);
let conversationId = null;
let dataRecords = [];
const won = (value) => `${Number(value || 0).toLocaleString('ko-KR')}원`;
const esc = (value) => String(value ?? '').replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[char]));
async function api(path, options) { const response = await fetch(path, options); const body = await response.json(); if (!response.ok) throw new Error(body.detail || body.error || '요청 실패'); return body; }
async function loadSummary() { const s = await api('/api/data/summary'); $('summary').innerHTML = [['분석 기간', s.period || '-'], ['데이터 포인트', `${s.count}개`], ['총 매출', won(s.metrics.total)], ['최근 추세', s.trend]].map(([label, value]) => `<div class="summary"><span>${label}</span><strong>${esc(value)}</strong></div>`).join(''); }
async function loadData() { dataRecords = await api('/api/data'); $('dataList').innerHTML = dataRecords.slice().reverse().slice(0, 80).map((item) => `<div class="data-item"><div><b>${esc(item.date)}</b><br><small>${esc(item.memo || '')} · ${won(item.value)}</small></div><button data-delete="${encodeURIComponent(item.id)}">삭제</button></div>`).join('') || '<p class="sub">데이터가 없습니다.</p>'; document.querySelectorAll('[data-delete]').forEach((button) => button.addEventListener('click', async () => { await api(`/api/data/${button.dataset.delete}`, { method: 'DELETE' }); await refresh(); })); }
async function loadConversations() { const conversations = await api('/api/conversations'); $('conversationList').innerHTML = conversations.map((item) => `<div class="conversation-item" data-conversation="${esc(item.id)}"><b>${esc(item.title)}</b><small>${esc(item.updated_at || '')}</small></div>`).join('') || '<p class="sub">저장된 대화가 없습니다.</p>'; document.querySelectorAll('[data-conversation]').forEach((item) => item.addEventListener('click', async () => { const conversation = await api(`/api/conversations/${encodeURIComponent(item.dataset.conversation)}`); conversationId = conversation.id; $('messages').innerHTML = conversation.messages.map((message) => `<div class="${message.role === 'user' ? 'user' : 'assistant'} message"><b>${message.role === 'user' ? '나' : '데이터 비서'}</b><p>${esc(message.content)}</p></div>`).join(''); })); }
async function refresh() { await Promise.all([loadSummary(), loadData(), loadConversations()]); }
$('chatForm').addEventListener('submit', async (event) => { event.preventDefault(); const input = $('chatInput'); const message = input.value.trim(); if (!message) return; $('messages').insertAdjacentHTML('beforeend', `<div class="user message"><b>나</b><p>${esc(message)}</p></div><div id="loading" class="assistant message loading"><b>데이터 비서</b><p>요약 데이터를 읽고 있습니다...</p></div>`); input.value = ''; try { const result = await api('/api/chat', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ message, conversation_id: conversationId }) }); conversationId = result.conversation_id; $('loading').outerHTML = `<div class="assistant message"><b>데이터 비서</b><p>${esc(result.answer)}</p></div>`; await loadConversations(); } catch (error) { $('loading').outerHTML = `<div class="assistant message"><b>오류</b><p>${esc(error.message)}</p></div>`; } $('messages').scrollTop = $('messages').scrollHeight; });
$('dataForm').addEventListener('submit', async (event) => { event.preventDefault(); await api('/api/data', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ date: $('dataDate').value, value: Number($('dataValue').value), memo: $('dataMemo').value }) }); event.target.reset(); await refresh(); });
$('refreshData').addEventListener('click', refresh);
$('newChat').addEventListener('click', () => { conversationId = null; $('messages').innerHTML = '<div class="assistant message"><b>데이터 비서</b><p>새 대화를 시작했습니다.</p></div>'; });
api('/health').then((health) => { $('health').textContent = health.openai ? 'Firebase · GPT 연결됨' : 'Firebase 연결 · GPT 보류'; }).catch(() => { $('health').textContent = '백엔드 연결 실패'; });
refresh().catch((error) => { $('health').textContent = error.message; });
